#! /bin/bash

mpi_loc=$(spack -C {{ env.config }} location -i cray-mpich)

. {{ env.mount }}/env/._default/*/activate.sh

install_pp() {(
    local OPTIND=1
    local arg
    local git_url=""       # -u "<url>"
    local git_tag=""       # -t "@<tag>"
    local extra_env=""     # -e "key1=value1 key2=value2"
    local extra_config=""  # -c "<myconfig>"
    local extra_config2="" # -q "<myconfig>"
    while getopts ':u:t:e:c:' arg; do
        case "${arg}" in
            u) git_url="${OPTARG}";;
            t) git_tag="${OPTARG}";;
            e) extra_env="${OPTARG}";;
            c) extra_config="${OPTARG}";;
            *) return 1 ;;# illegal option
        esac
    done
    IFS=' ' read -a extra_envs <<< "$extra_env"

    echo ""
    echo "installing python package from ${git_url}"

    export CXX=g++
    export CC=gcc
    export MAX_JOBS=250
    for env_assignment in "${extra_envs[@]}"; do
        export ${env_assignment}
    done
    eval "python \
        -m pip -vvv --no-input --no-cache-dir --disable-pip-version-check \
        install --no-build-isolation --no-warn-script-location --no-index \
        ${extra_config} \
        git+${git_url}${git_tag}"

    echo ""
)}

#install_pp -u "https://github.com/NVIDIA/TransformerEngine.git" -t "@56e0b351d0b7db6e622d3aa3eac6c6a1bf1ce4ab" \
#    -e "NVTE_FRAMEWORK=pytorch NVTE_WITH_USERBUFFERS=1 MPI_HOME=${mpi_loc}"

install_pp -u "https://github.com/openai/triton.git" -t "@989adb9a29496c22a36ef82ca69cad5dad536b9c#subdirectory=python" \
    -e "TRITON_BUILD_WITH_CLANG_LLD=true"

