#! /bin/bash

mpi_loc=$(spack -C {{ env.config }} location -i cray-mpich)
pybind11_loc=$(spack -C {{ env.config }} location -i py-pybind11)
py_venv_loc=$(spack -C {{ env.config }} location -i python-venv)
gcc_loc=$(spack -C {{ env.config }} location -i gcc@12%gcc@12)
#${py_venv_loc}/bin/python3 -m pip freeze

. {{ env.mount }}/env/._default/*/activate.sh

export CXX="${gcc_loc}/bin/g++"
export CC="${gcc_loc}/bin/gcc"
export MAX_JOBS=250
export TORCH_CUDA_ARCH_LIST=9.0

(
    # install py-torch-nvidia-apex manually

    export CPLUS_INCLUDE_PATH=${pybind11_loc}/include
    export LD_LIBRARY_PATH=${pybind11_loc}/lib

    python -m pip -vvv --no-input --no-cache-dir --disable-pip-version-check install --no-build-isolation --no-warn-script-location --no-index \
        --config-settings="--build-option=--cpp_ext" \
        --config-settings="--build-option=--cuda_ext" \
        git+https://github.com/NVIDIA/apex.git@master
)

(
    # install py-triton manually

    triton_home={{ env.mount }}/meta/extra/triton_home
    mkdir -p ${triton_home}

    export TRITON_HOME=${triton_home}

    python -m pip -vvv --no-input --no-cache-dir --disable-pip-version-check install --no-build-isolation --no-warn-script-location --no-index \
        git+https://github.com/openai/triton.git@989adb9a29496c22a36ef82ca69cad5dad536b9c#subdirectory=python
)

(
    python -m pip -vvv --no-input --no-cache-dir --disable-pip-version-check install --no-build-isolation --no-warn-script-location --no-index \
        git+https://github.com/mlcommons/logging.git@2.1.0-rc1
)

(
    python -m pip -vvv --no-input --no-cache-dir --disable-pip-version-check install --no-build-isolation --no-warn-script-location --no-index \
        git+https://github.com/NVIDIA/mlperf-common.git
)
